name: Build, Test and Benchmark Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Benchmark
        run: go test -bench=. ./...
  # golangci:
  #   name: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
  #         version: v1.29

  #         # Optional: working directory, useful for monorepos
  #         # working-directory: somedir

  #         # Optional: golangci-lint command line arguments.
  #         # args: --issues-exit-code=0

  #         # Optional: show only new issues if it's a pull request. The default value is `false`.
  #         # only-new-issues: true

  #         # Optional: if set to true then the action will use pre-installed Go
  #         # skip-go-installation: true